
//Cotent
export const NEW_RELEASE = 'TOP NEW';
export const FAVORITE_COURSES = 'Favorite Courses'
export const COURSE_IN_CATEGORY = 'Course In Categories'
export const COURSE_LEARNING = 'Continue Learning Courses'
export const RECOMMEND_FOR_YOU = 'Recommend For You'
export const SEE_ALL = 'See All >'
export const TOP_SELL = 'TOP SELL';
export const TOP_RATE = 'TOP RATE';
export const REQUIRE_LOGIN = 'You must login to see this page.'
export const INTERESTS = 'Interest'
export const PHONE_NUMBER = 'Phone'
export const CREATED_AT = 'Created At'
export const UPDATED_AT = 'Updated At'
export const LOGOUT = 'Logout'
export const UPDATE_INFO = 'UPDATE INFORMATION' 
export const CATEGORY = 'Categories'
export const PASSWORD = 'Password'
export const CREATE_ACCOUNT = 'Create An Account'
export const USER_NAME = 'Username'
export const RE_PASSWORD = 'Re-Password'
export const ALL = 'All'
export const COURSE = 'Course'
export const RESULT = 'Results'
export const LANGUAGE = 'Language'
export const THEME = 'Theme'
export const NAME = 'NAME'
export const UPDATE = 'Update'
export const OLD_PASSWORD = 'OLD PASSWORD'
export const NEW_PASSWORD = 'NEW PASSWORD'
export const CONFIRM_PASSWORD = 'CONFIRM PASSWORD'
export const REGISTERED = 'Registered'
export const LESSON = 'LESSON'
export const REVIEW = 'REVIEW'
export const LIKE = 'Like'
export const UNLIKE = 'Unlike'
export const SHARE = 'Share'
//Key Screen
export const BROWSE = 'Browse';
export const PROFILE = 'Profile';
export const COURSE_SUGGEST = 'Course Suggest';
export const COURSE_DETAIL = 'Course Detail';
export const LIST_COURSE = 'Courses';
export const AUTHOR = 'Author';
export const SKILL_DETAIL = 'Skill Detail';
export const FORGOT_PASSWORD = 'Forgot Password';
export const SETTING = 'Setting';
export const LOGIN = 'Login';
export const HOME = 'Home';
export const REGISTER = 'Sign Up';
export const DOWNLOAD = 'Download';
export const SEARCH = 'Search';
export const COURSE_TAB = 'Course';
export const AUTHOR_TAB = 'Author';
export const EDIT_INFO_SCREEN = 'Update Information';
export const CHANGE_PASSWORD = 'Change Password';
